Proyecto2/urls.py
from django.contrib import admin  
from django.urls import path  
from Proyecto2 import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('', views.index),  
    path('addnew',views.addnew),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  
#  </int:id></int:id></int:id>

music/music/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('admin/', admin.site.urls),

    # API Urls
    path('v1/api/', include([
        path('', include('core.api.urls')),
        path('accounts/', include('accounts.api.urls')),
    ])),
]

tableAdmin/urls.py
from django.contrib import admin  
from django.urls import path  
from tableAdmin import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('', views.index),  
    path('addnew',views.addnew),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  
#  </int:id></int:id></int:id>

tableuser/tableuser/urls.py
from django.contrib import admin  
from django.urls import path  
from tableuser import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('', views.index),  
    path('addnew',views.addnew),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]  

tableuser/tableuser/models.py
from django.db import models

class Music(models.Model):  
    name = models.CharField(max_length=100)  
    album = models.CharField(max_length=100)  
    artista = models.CharField(max_length=100)  
    year = models.CharField(max_length=100)  
    genero = models.CharField(max_length=100)  
  
    class Meta:  
        db_table = "songsuser"
        # app_label="Proyecto2"

tableuser/tableuser/forms.py
from django import forms  
from tableuser.models import Music  

class MusicForm(forms.ModelForm):  
    class Meta:  
        model = Music
        fields = ['name', 'album', 'artista', 'year','genero'] #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/
        widgets = { 'name': forms.TextInput(attrs={ 'class': 'form-control' }), 
                    'album': forms.TextInput(attrs={ 'class': 'form-control' }),
                    'artista': forms.TextInput(attrs={ 'class': 'form-control' }),
                    'year': forms.TextInput(attrs={ 'class': 'form-control' }),
                    'genero': forms.TextInput(attrs={ 'class': 'form-control' }),
      }

tableuser/tableuser/views.py
from django.shortcuts import render, redirect  
from tableuser.forms import MusicForm  
from tableuser.models import Music

# Create your views here.  
def addnew(request):  
    if request.method == "POST":  
        form = MusicForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/')  
            except:  
                pass 
    else:  
        form = MusicForm()  
    return render(request,'index.html',{'form':form})  
def index(request):  
    songs = Music.objects.all()  
    return render(request,"show.html",{'songs':songs})  

def edit(request, id):  
    song = Music.objects.get(id=id)  
    return render(request,'edit.html', {'song':song})  

def update(request, id):  
    song = Music.objects.get(id=id)  
    form = MusicForm(request.POST, instance = song)  
    if form.is_valid():  
        form.save()  
        return redirect("/")  
    return render(request, 'edit.html', {'song': song})  
def destroy(request, id):  
    song = Music.objects.get(id=id)  
    song.delete()  
    return redirect("/")  

tableuser/tableuser/templates/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
<meta charset="UTF-8">  
<title>{% block title %}{% endblock %}</title>
{% load static %}  
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
 
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
</head> 
<body>
<div class="container">
 <div class="row">
    {% block content %}{% endblock %}
 </div>
</div>
<script>
$(document).ready(function() {
    $('#bootstrapdatatable').DataTable({     
      "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
        "iDisplayLength": 10
       } 
    );
} );
</script>
</body> 
</html>

tableuser/tableuser/templates/edit.html
{% extends "base.html" %}
 
{% block title %}Add New Songs Records{% endblock title %}
 
{% block content %}
<div class="col-md-12">
    <h4>MUSIC</h4>  
 <form method="POST" class="post-form" action="/update/{{song.id}}">  
   {% csrf_token %}  
  <div class="container">  
 <br>  
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <h3>Update Details</h3>  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Song Id:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="id" id="id_id" required maxlength="20" value="{{ song.id }}"/>  
  </div>  
   </div>  
   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Song Name:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="name" id="id_name" required maxlength="100" value="{{ song.name }}" />  
  </div>  
   </div>  

  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Album Name:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="album" id="id_album" required maxlength="100" value="{{ song.album }}" />  
  </div>   
   </div>  

  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Artista Name:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="artista" id="id_artista" required maxlength="100" value="{{ song.artista }}" />  
  </div>  
   </div> 

   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Year:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="year" id="id_year" required maxlength="100" value="{{ song.year }}" />  
  </div>  
   </div> 

   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Genero:</label>  
  <div class="col-sm-4">  
   <input type="text" class="form-control" name="genero" id="genero" required maxlength="100" value="{{ song.genero }}" />  
  </div>  
   </div>  

  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <button type="submit" class="btn btn-success btn-lg">Update</button>  
  </div>  
   </div>  
  </div>  
 </form>  
{% endblock content %}   

tableuser/tableuser/templates/index.html
{% extends "base.html" %}
 
{% block title %}Add New Song{% endblock title %}
 
{% block content %}
<div class="col-md-12">
    <h4>Music</h4> 
         
 <form method="POST" class="post-form" action="/addnew">  
   {% csrf_token %}  
  <div class="container">  
 <br>  
  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <h3>Enter Details</h3>  
  </div>  
   </div>  
   
   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Song Name:</label>  
  <div class="col-sm-4">  
    {{ form.name }}  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Album Name:</label>  
  <div class="col-sm-4">  
    {{ form.album }}  
  </div>  
   </div>  
  <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Artist Name:</label>  
  <div class="col-sm-4">  
    {{ form.artista }}  
  </div>  
   </div>  

   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Year:</label>  
  <div class="col-sm-4">  
    {{ form.year }}  
  </div>  
   </div>  

   <div class="form-group row">  
  <label class="col-sm-2 col-form-label">Genero:</label>  
  <div class="col-sm-4">  
    {{ form.genero }}  
  </div>  
   </div>  

  <div class="form-group row">  
  <label class="col-sm-1 col-form-label"></label>  
  <div class="col-sm-4">  
  <button type="submit" class="btn btn-primary">Submit</button>  
  </div>  
   </div>  
  </div>  
 </form>  
</div> 
{% endblock content %} 

tableuser/tableuser/templates/show.html
{% extends "base.html" %}
 
{% block title %}Song Records{% endblock title %}
 
{% block content %}
 <div class="col-md-12">
        {% comment %} <h4>Song List</h4> <span><a href="/addnew" class="btn btn-primary">Add New Record</a></span>   {% endcomment %}
        <div class="table-responsive">
  <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th>ID</th>
                <th>Song Name</th>
                <th>Album name</th>
                <th>Artist Name</th>
                <th>Year</th>
                <th>Genero</th>
                <th></th> 
                <th></th> 
             </thead>
   <tbody>
   {% for song in songs %}  
    <tr>  
     <td><input type="checkbox" class="checkthis" /></td>
     <td>{{ song.id }}</td>  
     <td>{{ song.name }}</td>  
     <td>{{ song.album }}</td>  
     <td>{{ song.artista }}</td>  
     <td>{{ song.year }}</td>  
     <td>{{ song.genero }}</td>  


     <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="/edit/{{ song.id }}"   ></a></p></td>
     <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="/delete/{{ song.id }}"></a></p></td>  
    </tr>  
   {% endfor %} 
   </tbody>
         
  </table>
        </div>
    </div>
{% endblock content %}